// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKvFIvHelU4LjEHwMstFBHgrOOJVpuqSQ',
    appId: '1:344626967402:web:3bab68a576e849a534eb13',
    messagingSenderId: '344626967402',
    projectId: 'dressify-47e6a',
    authDomain: 'dressify-47e6a.firebaseapp.com',
    storageBucket: 'dressify-47e6a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBpyJLHlZDf6g8jRSogIg15LEMe0v3fq0',
    appId: '1:344626967402:android:58f32a25a8236e0334eb13',
    messagingSenderId: '344626967402',
    projectId: 'dressify-47e6a',
    storageBucket: 'dressify-47e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFCSEf5L46VitH7iHATVvQ8IeIpbjvylI',
    appId: '1:344626967402:ios:49b46268f531de7b34eb13',
    messagingSenderId: '344626967402',
    projectId: 'dressify-47e6a',
    storageBucket: 'dressify-47e6a.firebasestorage.app',
    iosBundleId: 'com.example.dressifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFCSEf5L46VitH7iHATVvQ8IeIpbjvylI',
    appId: '1:344626967402:ios:49b46268f531de7b34eb13',
    messagingSenderId: '344626967402',
    projectId: 'dressify-47e6a',
    storageBucket: 'dressify-47e6a.firebasestorage.app',
    iosBundleId: 'com.example.dressifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKvFIvHelU4LjEHwMstFBHgrOOJVpuqSQ',
    appId: '1:344626967402:web:3bab68a576e849a534eb13',
    messagingSenderId: '344626967402',
    projectId: 'dressify-47e6a',
    authDomain: 'dressify-47e6a.firebaseapp.com',
    storageBucket: 'dressify-47e6a.firebasestorage.app',
  );

}